version: '3.5'

services:

  child-react-components:
    container_name: child-react-components
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
